### ISSUE TITLE
Update stylelint to v8

### ISSUE THREAD

**Issue by vidhem** [suitcss/stylelint-suitcss#1]
[stylelint-config-suitcss](https://github.com/suitcss/stylelint-config-suitcss/blob/master/package.json) is using stylelint v8 in its dependencies but also uses stylelint-suitcss having stylelint v7.

An upgrade is required to v8 to fetch stylelint only at one place (in the global node_modules).

In a complex JS system, having both v7 and v8 is causing troubles for me.

See PR #2

**Comment by simonsmith** [comment]
Published as `2.0.0`
