### ISSUE TITLE
Question about disabling custom-property-no-outside-root

### ISSUE THREAD

**Issue by marr** [suitcss/stylelint-suitcss#4]
What is the risk in disabling this? I have some cases where I would like to override the value of a custom property inside a selector. Say:

```
:root {
  --color: blue;
}

.foo {
  --color: red;
}
```
I get the stylelint warning without disabling the rule, and I thought i would see what the issue with it is?

**Comment by simonsmith** [comment]
Custom properties cannot be precompiled when outside `:root` as they're tied to the DOM tree. That's the reason for the restriction. If your target browsers all support native custom properties then this can be safely disabled.
