### ISSUE TITLE
Update postcss-selector-parser

### ISSUE THREAD

**Issue by mjhenkes** [suitcss/stylelint-suitcss#6]
postcss-selector-parser is set to version 2.2.3, this version of postcss-selector-parser uses flatten 1.0.2 which is deprecated and causes warnings when installing dependencies.

postcss-selector-parser is up to version 6 which doesn't use flatten.

https://www.npmjs.com/package/postcss-selector-parser

**Comment by AlecRust** [comment]
Resolved in 4.0.0.

**Comment by mjhenkes** [comment]
@AlecRust Thank you! ❤️
